[package]
name = "rust-aes-file"
version = "0.1.1"
authors = ["raedion"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-stream = "0.2.0"
rust-crypto = "0.2.36"